package com.bohai.employeeSalary.dao;

import java.util.List;
import java.util.Map;

import com.bohai.employeeSalary.entity.CheckMessage;
import com.bohai.employeeSalary.entity.StaffInfo;
import com.bohai.employeeSalary.vo.QueryCheckMessageParamVO;

public interface CheckMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK_MESSAGE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK_MESSAGE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    int insert(CheckMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK_MESSAGE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    int insertSelective(CheckMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK_MESSAGE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    CheckMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK_MESSAGE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    int updateByPrimaryKeySelective(CheckMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK_MESSAGE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    int updateByPrimaryKey(CheckMessage record);

    /**
     * 查询所有待审核信息
     * */
	List<CheckMessage> queryCheckMessages(Map<String,Object> map);

	/**
	 * 按条件查询审核信息
	 * */
	List<CheckMessage> selectByCheckCondition(QueryCheckMessageParamVO paramVO);

	List<CheckMessage> selectBySubmitter(String userName);
}