package com.bohai.employeeSalary.dao;

import com.bohai.employeeSalary.entity.Department;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    int deleteByPrimaryKey(String depNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    Department selectByPrimaryKey(String depNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    int updateByPrimaryKey(Department record);
}