package com.bohai.employeeSalary.dao;

import java.util.List;

import com.bohai.employeeSalary.entity.Department;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Tue Aug 15 14:12:42 CST 2017
     */
    int deleteByPrimaryKey(String depNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Tue Aug 15 14:12:42 CST 2017
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Tue Aug 15 14:12:42 CST 2017
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Tue Aug 15 14:12:42 CST 2017
     */
    Department selectByPrimaryKey(String depNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Tue Aug 15 14:12:42 CST 2017
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated Tue Aug 15 14:12:42 CST 2017
     */
    int updateByPrimaryKey(Department record);

	List<Department> queryDepartments();
}