package com.bohai.employeeSalary.dao;

import com.bohai.employeeSalary.entity.StaffInfo;

public interface StaffInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Tue Aug 15 13:38:03 CST 2017
     */
    int deleteByPrimaryKey(String staffNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Tue Aug 15 13:38:03 CST 2017
     */
    int insert(StaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Tue Aug 15 13:38:03 CST 2017
     */
    int insertSelective(StaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Tue Aug 15 13:38:03 CST 2017
     */
    StaffInfo selectByPrimaryKey(String staffNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Tue Aug 15 13:38:03 CST 2017
     */
    int updateByPrimaryKeySelective(StaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Tue Aug 15 13:38:03 CST 2017
     */
    int updateByPrimaryKey(StaffInfo record);
    
    /**
     * 标记员工离职
     * 
     * */
    int signOffStaff(StaffInfo record);
    
    /**
     * 试用期员工转正
     * */
    int signOnProbation(StaffInfo record);
}