package com.bohai.employeeSalary.dao;

import com.bohai.employeeSalary.entity.StaffSalary;

public interface StaffSalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_SALARY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    int insert(StaffSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_SALARY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    int insertSelective(StaffSalary record);
}