package com.bohai.employeeSalary.dao;

import com.bohai.employeeSalary.entity.StaffInfo;

public interface StaffInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    int deleteByPrimaryKey(String staffNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    int insert(StaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    int insertSelective(StaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    StaffInfo selectByPrimaryKey(String staffNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    int updateByPrimaryKeySelective(StaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_INFO
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    int updateByPrimaryKey(StaffInfo record);
}