package com.bohai.employeeSalary.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class CheckMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.ID
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.PROBATION_DATE_START
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date probationDateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.FORMAL_DATE_START
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date formalDateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.LEAVE_DATE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date leaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.NAME
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.ID_NUMBER
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.STAFF_NUMBER
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String staffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.POSITION_SALARY
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String positionSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.WORK_YEARS
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String workYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.EMAIL
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.REMARK
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.DEPARTMENT_ID
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.IS_LEAVE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String departmentName;
    
    private String isLeave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.CREATE_TIME
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.UPDATE_TIME
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.IS_PROBATION
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String isProbation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.COEFFICEIENT
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String coefficeient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.SKILL_SALARY
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String skillSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK_MESSAGE.TAGE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String tage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.ID
     *
     * @return the value of CHECK_MESSAGE.ID
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    private String submitter;
    
    private String checker;
   
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date submitTime;
   
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date checkTime;
    
    private String submitType;
    
    private String approvalOpinion;
    
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.ID
     *
     * @param id the value for CHECK_MESSAGE.ID
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.PROBATION_DATE_START
     *
     * @return the value of CHECK_MESSAGE.PROBATION_DATE_START
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public Date getProbationDateStart() {
        return probationDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.PROBATION_DATE_START
     *
     * @param probationDateStart the value for CHECK_MESSAGE.PROBATION_DATE_START
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setProbationDateStart(Date probationDateStart) {
        this.probationDateStart = probationDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.FORMAL_DATE_START
     *
     * @return the value of CHECK_MESSAGE.FORMAL_DATE_START
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public Date getFormalDateStart() {
        return formalDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.FORMAL_DATE_START
     *
     * @param formalDateStart the value for CHECK_MESSAGE.FORMAL_DATE_START
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setFormalDateStart(Date formalDateStart) {
        this.formalDateStart = formalDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.LEAVE_DATE
     *
     * @return the value of CHECK_MESSAGE.LEAVE_DATE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.LEAVE_DATE
     *
     * @param leaveDate the value for CHECK_MESSAGE.LEAVE_DATE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.NAME
     *
     * @return the value of CHECK_MESSAGE.NAME
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.NAME
     *
     * @param name the value for CHECK_MESSAGE.NAME
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.ID_NUMBER
     *
     * @return the value of CHECK_MESSAGE.ID_NUMBER
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.ID_NUMBER
     *
     * @param idNumber the value for CHECK_MESSAGE.ID_NUMBER
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.STAFF_NUMBER
     *
     * @return the value of CHECK_MESSAGE.STAFF_NUMBER
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getStaffNumber() {
        return staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.STAFF_NUMBER
     *
     * @param staffNumber the value for CHECK_MESSAGE.STAFF_NUMBER
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setStaffNumber(String staffNumber) {
        this.staffNumber = staffNumber == null ? null : staffNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.POSITION_SALARY
     *
     * @return the value of CHECK_MESSAGE.POSITION_SALARY
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getPositionSalary() {
        return positionSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.POSITION_SALARY
     *
     * @param positionSalary the value for CHECK_MESSAGE.POSITION_SALARY
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setPositionSalary(String positionSalary) {
        this.positionSalary = positionSalary == null ? null : positionSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.WORK_YEARS
     *
     * @return the value of CHECK_MESSAGE.WORK_YEARS
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getWorkYears() {
        return workYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.WORK_YEARS
     *
     * @param workYears the value for CHECK_MESSAGE.WORK_YEARS
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setWorkYears(String workYears) {
        this.workYears = workYears == null ? null : workYears.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.EMAIL
     *
     * @return the value of CHECK_MESSAGE.EMAIL
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.EMAIL
     *
     * @param email the value for CHECK_MESSAGE.EMAIL
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.REMARK
     *
     * @return the value of CHECK_MESSAGE.REMARK
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.REMARK
     *
     * @param remark the value for CHECK_MESSAGE.REMARK
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.DEPARTMENT_ID
     *
     * @return the value of CHECK_MESSAGE.DEPARTMENT_ID
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.DEPARTMENT_ID
     *
     * @param departmentId the value for CHECK_MESSAGE.DEPARTMENT_ID
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.IS_LEAVE
     *
     * @return the value of CHECK_MESSAGE.IS_LEAVE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getIsLeave() {
        return isLeave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.IS_LEAVE
     *
     * @param isLeave the value for CHECK_MESSAGE.IS_LEAVE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setIsLeave(String isLeave) {
        this.isLeave = isLeave == null ? null : isLeave.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.CREATE_TIME
     *
     * @return the value of CHECK_MESSAGE.CREATE_TIME
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.CREATE_TIME
     *
     * @param createTime the value for CHECK_MESSAGE.CREATE_TIME
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.UPDATE_TIME
     *
     * @return the value of CHECK_MESSAGE.UPDATE_TIME
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.UPDATE_TIME
     *
     * @param updateTime the value for CHECK_MESSAGE.UPDATE_TIME
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.IS_PROBATION
     *
     * @return the value of CHECK_MESSAGE.IS_PROBATION
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getIsProbation() {
        return isProbation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.IS_PROBATION
     *
     * @param isProbation the value for CHECK_MESSAGE.IS_PROBATION
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setIsProbation(String isProbation) {
        this.isProbation = isProbation == null ? null : isProbation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.COEFFICEIENT
     *
     * @return the value of CHECK_MESSAGE.COEFFICEIENT
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getCoefficeient() {
        return coefficeient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.COEFFICEIENT
     *
     * @param coefficeient the value for CHECK_MESSAGE.COEFFICEIENT
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setCoefficeient(String coefficeient) {
        this.coefficeient = coefficeient == null ? null : coefficeient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.SKILL_SALARY
     *
     * @return the value of CHECK_MESSAGE.SKILL_SALARY
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getSkillSalary() {
        return skillSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.SKILL_SALARY
     *
     * @param skillSalary the value for CHECK_MESSAGE.SKILL_SALARY
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setSkillSalary(String skillSalary) {
        this.skillSalary = skillSalary == null ? null : skillSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK_MESSAGE.TAGE
     *
     * @return the value of CHECK_MESSAGE.TAGE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public String getTage() {
        return tage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK_MESSAGE.TAGE
     *
     * @param tage the value for CHECK_MESSAGE.TAGE
     *
     * @mbggenerated Wed Sep 06 15:18:02 CST 2017
     */
    public void setTage(String tage) {
        this.tage = tage == null ? null : tage.trim();
    }

	public String getSubmitter() {
		return submitter;
	}

	public void setSubmitter(String submitter) {
		this.submitter = submitter;
	}

	public String getChecker() {
		return checker;
	}

	public void setChecker(String checker) {
		this.checker = checker;
	}

	public Date getSubmitTime() {
		return submitTime;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	public Date getCheckTime() {
		return checkTime;
	}

	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	public String getSubmitType() {
		return submitType;
	}

	public void setSubmitType(String string) {
		this.submitType = string;
	}

	public String getApprovalOpinion() {
		return approvalOpinion;
	}

	public void setApprovalOpinion(String approvalOpinion) {
		this.approvalOpinion = approvalOpinion;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}
	
}