package com.bohai.employeeSalary.entity;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEP_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    private String depNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEP_NAME
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEP_STATE
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    private String depState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEP_NUMBER
     *
     * @return the value of DEPARTMENT.DEP_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    public String getDepNumber() {
        return depNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEP_NUMBER
     *
     * @param depNumber the value for DEPARTMENT.DEP_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    public void setDepNumber(String depNumber) {
        this.depNumber = depNumber == null ? null : depNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEP_NAME
     *
     * @return the value of DEPARTMENT.DEP_NAME
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEP_NAME
     *
     * @param depName the value for DEPARTMENT.DEP_NAME
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEP_STATE
     *
     * @return the value of DEPARTMENT.DEP_STATE
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    public String getDepState() {
        return depState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEP_STATE
     *
     * @param depState the value for DEPARTMENT.DEP_STATE
     *
     * @mbggenerated Mon Aug 14 13:29:37 CST 2017
     */
    public void setDepState(String depState) {
        this.depState = depState == null ? null : depState.trim();
    }
}