package com.bohai.employeeSalary.entity;

import java.util.Date;

public class SalaryDate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_DATE.TDATE
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    private Date tdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_DATE.TYEAR
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    private String tyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_DATE.TMONTH
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    private String tmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_DATE.TDAY
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    private String tday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_DATE.TWEEK
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    private String tweek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_DATE.TIW
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    private String tiw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_DATE.TSEASON
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    private String tseason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_DATE.REMARK
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SALARY_DATE.TYPE
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_DATE.TDATE
     *
     * @return the value of SALARY_DATE.TDATE
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public Date getTdate() {
        return tdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_DATE.TDATE
     *
     * @param tdate the value for SALARY_DATE.TDATE
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public void setTdate(Date tdate) {
        this.tdate = tdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_DATE.TYEAR
     *
     * @return the value of SALARY_DATE.TYEAR
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public String getTyear() {
        return tyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_DATE.TYEAR
     *
     * @param tyear the value for SALARY_DATE.TYEAR
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public void setTyear(String tyear) {
        this.tyear = tyear == null ? null : tyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_DATE.TMONTH
     *
     * @return the value of SALARY_DATE.TMONTH
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public String getTmonth() {
        return tmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_DATE.TMONTH
     *
     * @param tmonth the value for SALARY_DATE.TMONTH
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public void setTmonth(String tmonth) {
        this.tmonth = tmonth == null ? null : tmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_DATE.TDAY
     *
     * @return the value of SALARY_DATE.TDAY
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public String getTday() {
        return tday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_DATE.TDAY
     *
     * @param tday the value for SALARY_DATE.TDAY
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public void setTday(String tday) {
        this.tday = tday == null ? null : tday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_DATE.TWEEK
     *
     * @return the value of SALARY_DATE.TWEEK
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public String getTweek() {
        return tweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_DATE.TWEEK
     *
     * @param tweek the value for SALARY_DATE.TWEEK
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public void setTweek(String tweek) {
        this.tweek = tweek == null ? null : tweek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_DATE.TIW
     *
     * @return the value of SALARY_DATE.TIW
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public String getTiw() {
        return tiw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_DATE.TIW
     *
     * @param tiw the value for SALARY_DATE.TIW
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public void setTiw(String tiw) {
        this.tiw = tiw == null ? null : tiw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_DATE.TSEASON
     *
     * @return the value of SALARY_DATE.TSEASON
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public String getTseason() {
        return tseason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_DATE.TSEASON
     *
     * @param tseason the value for SALARY_DATE.TSEASON
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public void setTseason(String tseason) {
        this.tseason = tseason == null ? null : tseason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_DATE.REMARK
     *
     * @return the value of SALARY_DATE.REMARK
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_DATE.REMARK
     *
     * @param remark the value for SALARY_DATE.REMARK
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SALARY_DATE.TYPE
     *
     * @return the value of SALARY_DATE.TYPE
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SALARY_DATE.TYPE
     *
     * @param type the value for SALARY_DATE.TYPE
     *
     * @mbggenerated Wed Aug 23 15:55:47 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}