package com.bohai.employeeSalary.entity;

import java.util.Date;

public class StaffInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.STAFF_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String staffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.PROBATION_DATE_START
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private Date probationDateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.FORMAL_DATE_START
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private Date formalDateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.LEAVE_DATE
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private Date leaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.NAME
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.ID_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.POSITION_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String positionSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.PERFORMANCE_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String performanceSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.WORK_YEARS
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String workYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.SKILL_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String skillSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.SHOULD_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String shouldSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.WARM_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String warmCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.HOUSING_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String housingCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.PENSION_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String pensionCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.UNEMPLOYMENT_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String unemploymentCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.MEDICAL_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String medicalCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.SUPPLEMENT_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String supplementCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.SOCIAL_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String socialCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.TAX_BASE
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String taxBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.INDIVIDUAL_TAX
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String individualTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.OTHER_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String otherCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.EMAIL
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.REMARK
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_INFO.DEPARTMENT_ID
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    private String departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.STAFF_NUMBER
     *
     * @return the value of STAFF_INFO.STAFF_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getStaffNumber() {
        return staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.STAFF_NUMBER
     *
     * @param staffNumber the value for STAFF_INFO.STAFF_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setStaffNumber(String staffNumber) {
        this.staffNumber = staffNumber == null ? null : staffNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.PROBATION_DATE_START
     *
     * @return the value of STAFF_INFO.PROBATION_DATE_START
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public Date getProbationDateStart() {
        return probationDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.PROBATION_DATE_START
     *
     * @param probationDateStart the value for STAFF_INFO.PROBATION_DATE_START
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setProbationDateStart(Date probationDateStart) {
        this.probationDateStart = probationDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.FORMAL_DATE_START
     *
     * @return the value of STAFF_INFO.FORMAL_DATE_START
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public Date getFormalDateStart() {
        return formalDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.FORMAL_DATE_START
     *
     * @param formalDateStart the value for STAFF_INFO.FORMAL_DATE_START
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setFormalDateStart(Date formalDateStart) {
        this.formalDateStart = formalDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.LEAVE_DATE
     *
     * @return the value of STAFF_INFO.LEAVE_DATE
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.LEAVE_DATE
     *
     * @param leaveDate the value for STAFF_INFO.LEAVE_DATE
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.NAME
     *
     * @return the value of STAFF_INFO.NAME
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.NAME
     *
     * @param name the value for STAFF_INFO.NAME
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.ID_NUMBER
     *
     * @return the value of STAFF_INFO.ID_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.ID_NUMBER
     *
     * @param idNumber the value for STAFF_INFO.ID_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.POSITION_SALARY
     *
     * @return the value of STAFF_INFO.POSITION_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getPositionSalary() {
        return positionSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.POSITION_SALARY
     *
     * @param positionSalary the value for STAFF_INFO.POSITION_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setPositionSalary(String positionSalary) {
        this.positionSalary = positionSalary == null ? null : positionSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.PERFORMANCE_SALARY
     *
     * @return the value of STAFF_INFO.PERFORMANCE_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getPerformanceSalary() {
        return performanceSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.PERFORMANCE_SALARY
     *
     * @param performanceSalary the value for STAFF_INFO.PERFORMANCE_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setPerformanceSalary(String performanceSalary) {
        this.performanceSalary = performanceSalary == null ? null : performanceSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.WORK_YEARS
     *
     * @return the value of STAFF_INFO.WORK_YEARS
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getWorkYears() {
        return workYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.WORK_YEARS
     *
     * @param workYears the value for STAFF_INFO.WORK_YEARS
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setWorkYears(String workYears) {
        this.workYears = workYears == null ? null : workYears.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.SKILL_SALARY
     *
     * @return the value of STAFF_INFO.SKILL_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getSkillSalary() {
        return skillSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.SKILL_SALARY
     *
     * @param skillSalary the value for STAFF_INFO.SKILL_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setSkillSalary(String skillSalary) {
        this.skillSalary = skillSalary == null ? null : skillSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.SHOULD_SALARY
     *
     * @return the value of STAFF_INFO.SHOULD_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getShouldSalary() {
        return shouldSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.SHOULD_SALARY
     *
     * @param shouldSalary the value for STAFF_INFO.SHOULD_SALARY
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setShouldSalary(String shouldSalary) {
        this.shouldSalary = shouldSalary == null ? null : shouldSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.WARM_COST
     *
     * @return the value of STAFF_INFO.WARM_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getWarmCost() {
        return warmCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.WARM_COST
     *
     * @param warmCost the value for STAFF_INFO.WARM_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setWarmCost(String warmCost) {
        this.warmCost = warmCost == null ? null : warmCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.HOUSING_COST
     *
     * @return the value of STAFF_INFO.HOUSING_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getHousingCost() {
        return housingCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.HOUSING_COST
     *
     * @param housingCost the value for STAFF_INFO.HOUSING_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setHousingCost(String housingCost) {
        this.housingCost = housingCost == null ? null : housingCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.PENSION_COST
     *
     * @return the value of STAFF_INFO.PENSION_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getPensionCost() {
        return pensionCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.PENSION_COST
     *
     * @param pensionCost the value for STAFF_INFO.PENSION_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setPensionCost(String pensionCost) {
        this.pensionCost = pensionCost == null ? null : pensionCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.UNEMPLOYMENT_COST
     *
     * @return the value of STAFF_INFO.UNEMPLOYMENT_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getUnemploymentCost() {
        return unemploymentCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.UNEMPLOYMENT_COST
     *
     * @param unemploymentCost the value for STAFF_INFO.UNEMPLOYMENT_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setUnemploymentCost(String unemploymentCost) {
        this.unemploymentCost = unemploymentCost == null ? null : unemploymentCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.MEDICAL_COST
     *
     * @return the value of STAFF_INFO.MEDICAL_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getMedicalCost() {
        return medicalCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.MEDICAL_COST
     *
     * @param medicalCost the value for STAFF_INFO.MEDICAL_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setMedicalCost(String medicalCost) {
        this.medicalCost = medicalCost == null ? null : medicalCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.SUPPLEMENT_COST
     *
     * @return the value of STAFF_INFO.SUPPLEMENT_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getSupplementCost() {
        return supplementCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.SUPPLEMENT_COST
     *
     * @param supplementCost the value for STAFF_INFO.SUPPLEMENT_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setSupplementCost(String supplementCost) {
        this.supplementCost = supplementCost == null ? null : supplementCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.SOCIAL_COST
     *
     * @return the value of STAFF_INFO.SOCIAL_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getSocialCost() {
        return socialCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.SOCIAL_COST
     *
     * @param socialCost the value for STAFF_INFO.SOCIAL_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setSocialCost(String socialCost) {
        this.socialCost = socialCost == null ? null : socialCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.TAX_BASE
     *
     * @return the value of STAFF_INFO.TAX_BASE
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getTaxBase() {
        return taxBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.TAX_BASE
     *
     * @param taxBase the value for STAFF_INFO.TAX_BASE
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setTaxBase(String taxBase) {
        this.taxBase = taxBase == null ? null : taxBase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.INDIVIDUAL_TAX
     *
     * @return the value of STAFF_INFO.INDIVIDUAL_TAX
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getIndividualTax() {
        return individualTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.INDIVIDUAL_TAX
     *
     * @param individualTax the value for STAFF_INFO.INDIVIDUAL_TAX
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setIndividualTax(String individualTax) {
        this.individualTax = individualTax == null ? null : individualTax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.OTHER_COST
     *
     * @return the value of STAFF_INFO.OTHER_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getOtherCost() {
        return otherCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.OTHER_COST
     *
     * @param otherCost the value for STAFF_INFO.OTHER_COST
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setOtherCost(String otherCost) {
        this.otherCost = otherCost == null ? null : otherCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.EMAIL
     *
     * @return the value of STAFF_INFO.EMAIL
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.EMAIL
     *
     * @param email the value for STAFF_INFO.EMAIL
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.REMARK
     *
     * @return the value of STAFF_INFO.REMARK
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.REMARK
     *
     * @param remark the value for STAFF_INFO.REMARK
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_INFO.DEPARTMENT_ID
     *
     * @return the value of STAFF_INFO.DEPARTMENT_ID
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_INFO.DEPARTMENT_ID
     *
     * @param departmentId the value for STAFF_INFO.DEPARTMENT_ID
     *
     * @mbggenerated Mon Aug 14 13:28:42 CST 2017
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }
}