package com.bohai.employeeSalary.entity;

import java.util.Date;

public class StaffSalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.STAFF_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    private String staffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    private String staffDepartmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.STAFF_SALARY
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    private String staffSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.SALARY_DATE
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    private Date salaryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.SALARY_OTHER
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    private String salaryOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.OTHER_REMARK
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    private String otherRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.STAFF_NUMBER
     *
     * @return the value of STAFF_SALARY.STAFF_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public String getStaffNumber() {
        return staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.STAFF_NUMBER
     *
     * @param staffNumber the value for STAFF_SALARY.STAFF_NUMBER
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public void setStaffNumber(String staffNumber) {
        this.staffNumber = staffNumber == null ? null : staffNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @return the value of STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public String getStaffDepartmentId() {
        return staffDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @param staffDepartmentId the value for STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public void setStaffDepartmentId(String staffDepartmentId) {
        this.staffDepartmentId = staffDepartmentId == null ? null : staffDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.STAFF_SALARY
     *
     * @return the value of STAFF_SALARY.STAFF_SALARY
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public String getStaffSalary() {
        return staffSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.STAFF_SALARY
     *
     * @param staffSalary the value for STAFF_SALARY.STAFF_SALARY
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public void setStaffSalary(String staffSalary) {
        this.staffSalary = staffSalary == null ? null : staffSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.SALARY_DATE
     *
     * @return the value of STAFF_SALARY.SALARY_DATE
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public Date getSalaryDate() {
        return salaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.SALARY_DATE
     *
     * @param salaryDate the value for STAFF_SALARY.SALARY_DATE
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public void setSalaryDate(Date salaryDate) {
        this.salaryDate = salaryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.SALARY_OTHER
     *
     * @return the value of STAFF_SALARY.SALARY_OTHER
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public String getSalaryOther() {
        return salaryOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.SALARY_OTHER
     *
     * @param salaryOther the value for STAFF_SALARY.SALARY_OTHER
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public void setSalaryOther(String salaryOther) {
        this.salaryOther = salaryOther == null ? null : salaryOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.OTHER_REMARK
     *
     * @return the value of STAFF_SALARY.OTHER_REMARK
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public String getOtherRemark() {
        return otherRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.OTHER_REMARK
     *
     * @param otherRemark the value for STAFF_SALARY.OTHER_REMARK
     *
     * @mbggenerated Mon Aug 14 13:27:04 CST 2017
     */
    public void setOtherRemark(String otherRemark) {
        this.otherRemark = otherRemark == null ? null : otherRemark.trim();
    }
}