package com.bohai.employeeSalary.entity;

public class StaffSalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.STAFF_NUMBER
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String staffNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String staffDepartmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.ACHIEMENT_SALARY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String achiementSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PAY_DATE
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.SALARY_OTHER
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String salaryOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.OTHER_REMARK
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String otherRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.CREATE_TIME
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PAY_BASE
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String payBase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PENSION_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String pensionPersonal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PENSION_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String pensionCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.MEDICAL_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String medicalPersonal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.MEDICAL_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String medicalCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.UNEMPLOYMENT_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String unemploymentPersonal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.UNEMPLOYMENT_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String unemploymentCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.INJURY_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String injuryCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.BIRTH_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String birthCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PERSONAL_RESERVE1
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String personalReserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PERSONAL_RESERVE2
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String personalReserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.COMPANY_RESERVE1
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String companyReserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.COMPANY_RESERVE2
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String companyReserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.WARM_SUBSIDY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String warmSubsidy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PENSION_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String pensionPersonalPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PENSION_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String pensionCompanyPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.MEDICAL_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String medicalPersonalPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.MEDICAL_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String medicalCompanyPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.UNEMPLOYMENT_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String unemploymentPersonalPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.UNEMPLOYMENT_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String unemploymentCompanyPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.INJURY_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String injuryCompanyPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.BIRTH_COMPAY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String birthCompayPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.ACTUAL_SALARY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String actualSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PERSONAL_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String personalTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.COMPANY_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String companyTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.PAYMENT_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String paymentTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_BASE_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseBasePersonal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_BASE_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseBaseCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_SUPPLY_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseSupplyPersonal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_SUPPLY_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseSupplyCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_BASE_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseBasePersonalPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_BASE_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseBaseCompanyPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_SUPPLY_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseSupplyPersonalPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_SUPPLY_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseSupplyCompanyPercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_PERSONAL_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String housePersonalTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_COMPANY_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseCompanyTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAFF_SALARY.HOUSE_TOATAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    private String houseToatal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.STAFF_NUMBER
     *
     * @return the value of STAFF_SALARY.STAFF_NUMBER
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getStaffNumber() {
        return staffNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.STAFF_NUMBER
     *
     * @param staffNumber the value for STAFF_SALARY.STAFF_NUMBER
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setStaffNumber(String staffNumber) {
        this.staffNumber = staffNumber == null ? null : staffNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @return the value of STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getStaffDepartmentId() {
        return staffDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @param staffDepartmentId the value for STAFF_SALARY.STAFF_DEPARTMENT_ID
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setStaffDepartmentId(String staffDepartmentId) {
        this.staffDepartmentId = staffDepartmentId == null ? null : staffDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.ACHIEMENT_SALARY
     *
     * @return the value of STAFF_SALARY.ACHIEMENT_SALARY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getAchiementSalary() {
        return achiementSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.ACHIEMENT_SALARY
     *
     * @param achiementSalary the value for STAFF_SALARY.ACHIEMENT_SALARY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setAchiementSalary(String achiementSalary) {
        this.achiementSalary = achiementSalary == null ? null : achiementSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PAY_DATE
     *
     * @return the value of STAFF_SALARY.PAY_DATE
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PAY_DATE
     *
     * @param payDate the value for STAFF_SALARY.PAY_DATE
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate == null ? null : payDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.SALARY_OTHER
     *
     * @return the value of STAFF_SALARY.SALARY_OTHER
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getSalaryOther() {
        return salaryOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.SALARY_OTHER
     *
     * @param salaryOther the value for STAFF_SALARY.SALARY_OTHER
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setSalaryOther(String salaryOther) {
        this.salaryOther = salaryOther == null ? null : salaryOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.OTHER_REMARK
     *
     * @return the value of STAFF_SALARY.OTHER_REMARK
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getOtherRemark() {
        return otherRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.OTHER_REMARK
     *
     * @param otherRemark the value for STAFF_SALARY.OTHER_REMARK
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setOtherRemark(String otherRemark) {
        this.otherRemark = otherRemark == null ? null : otherRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.CREATE_TIME
     *
     * @return the value of STAFF_SALARY.CREATE_TIME
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.CREATE_TIME
     *
     * @param createTime the value for STAFF_SALARY.CREATE_TIME
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.UPDATE_TIME
     *
     * @return the value of STAFF_SALARY.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.UPDATE_TIME
     *
     * @param updateTime the value for STAFF_SALARY.UPDATE_TIME
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PAY_BASE
     *
     * @return the value of STAFF_SALARY.PAY_BASE
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPayBase() {
        return payBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PAY_BASE
     *
     * @param payBase the value for STAFF_SALARY.PAY_BASE
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPayBase(String payBase) {
        this.payBase = payBase == null ? null : payBase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PENSION_PERSONAL
     *
     * @return the value of STAFF_SALARY.PENSION_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPensionPersonal() {
        return pensionPersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PENSION_PERSONAL
     *
     * @param pensionPersonal the value for STAFF_SALARY.PENSION_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPensionPersonal(String pensionPersonal) {
        this.pensionPersonal = pensionPersonal == null ? null : pensionPersonal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PENSION_COMPANY
     *
     * @return the value of STAFF_SALARY.PENSION_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPensionCompany() {
        return pensionCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PENSION_COMPANY
     *
     * @param pensionCompany the value for STAFF_SALARY.PENSION_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPensionCompany(String pensionCompany) {
        this.pensionCompany = pensionCompany == null ? null : pensionCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.MEDICAL_PERSONAL
     *
     * @return the value of STAFF_SALARY.MEDICAL_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getMedicalPersonal() {
        return medicalPersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.MEDICAL_PERSONAL
     *
     * @param medicalPersonal the value for STAFF_SALARY.MEDICAL_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setMedicalPersonal(String medicalPersonal) {
        this.medicalPersonal = medicalPersonal == null ? null : medicalPersonal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.MEDICAL_COMPANY
     *
     * @return the value of STAFF_SALARY.MEDICAL_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getMedicalCompany() {
        return medicalCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.MEDICAL_COMPANY
     *
     * @param medicalCompany the value for STAFF_SALARY.MEDICAL_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setMedicalCompany(String medicalCompany) {
        this.medicalCompany = medicalCompany == null ? null : medicalCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.UNEMPLOYMENT_PERSONAL
     *
     * @return the value of STAFF_SALARY.UNEMPLOYMENT_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getUnemploymentPersonal() {
        return unemploymentPersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.UNEMPLOYMENT_PERSONAL
     *
     * @param unemploymentPersonal the value for STAFF_SALARY.UNEMPLOYMENT_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setUnemploymentPersonal(String unemploymentPersonal) {
        this.unemploymentPersonal = unemploymentPersonal == null ? null : unemploymentPersonal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.UNEMPLOYMENT_COMPANY
     *
     * @return the value of STAFF_SALARY.UNEMPLOYMENT_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getUnemploymentCompany() {
        return unemploymentCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.UNEMPLOYMENT_COMPANY
     *
     * @param unemploymentCompany the value for STAFF_SALARY.UNEMPLOYMENT_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setUnemploymentCompany(String unemploymentCompany) {
        this.unemploymentCompany = unemploymentCompany == null ? null : unemploymentCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.INJURY_COMPANY
     *
     * @return the value of STAFF_SALARY.INJURY_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getInjuryCompany() {
        return injuryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.INJURY_COMPANY
     *
     * @param injuryCompany the value for STAFF_SALARY.INJURY_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setInjuryCompany(String injuryCompany) {
        this.injuryCompany = injuryCompany == null ? null : injuryCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.BIRTH_COMPANY
     *
     * @return the value of STAFF_SALARY.BIRTH_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getBirthCompany() {
        return birthCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.BIRTH_COMPANY
     *
     * @param birthCompany the value for STAFF_SALARY.BIRTH_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setBirthCompany(String birthCompany) {
        this.birthCompany = birthCompany == null ? null : birthCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PERSONAL_RESERVE1
     *
     * @return the value of STAFF_SALARY.PERSONAL_RESERVE1
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPersonalReserve1() {
        return personalReserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PERSONAL_RESERVE1
     *
     * @param personalReserve1 the value for STAFF_SALARY.PERSONAL_RESERVE1
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPersonalReserve1(String personalReserve1) {
        this.personalReserve1 = personalReserve1 == null ? null : personalReserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PERSONAL_RESERVE2
     *
     * @return the value of STAFF_SALARY.PERSONAL_RESERVE2
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPersonalReserve2() {
        return personalReserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PERSONAL_RESERVE2
     *
     * @param personalReserve2 the value for STAFF_SALARY.PERSONAL_RESERVE2
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPersonalReserve2(String personalReserve2) {
        this.personalReserve2 = personalReserve2 == null ? null : personalReserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.COMPANY_RESERVE1
     *
     * @return the value of STAFF_SALARY.COMPANY_RESERVE1
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getCompanyReserve1() {
        return companyReserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.COMPANY_RESERVE1
     *
     * @param companyReserve1 the value for STAFF_SALARY.COMPANY_RESERVE1
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setCompanyReserve1(String companyReserve1) {
        this.companyReserve1 = companyReserve1 == null ? null : companyReserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.COMPANY_RESERVE2
     *
     * @return the value of STAFF_SALARY.COMPANY_RESERVE2
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getCompanyReserve2() {
        return companyReserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.COMPANY_RESERVE2
     *
     * @param companyReserve2 the value for STAFF_SALARY.COMPANY_RESERVE2
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setCompanyReserve2(String companyReserve2) {
        this.companyReserve2 = companyReserve2 == null ? null : companyReserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.WARM_SUBSIDY
     *
     * @return the value of STAFF_SALARY.WARM_SUBSIDY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getWarmSubsidy() {
        return warmSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.WARM_SUBSIDY
     *
     * @param warmSubsidy the value for STAFF_SALARY.WARM_SUBSIDY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setWarmSubsidy(String warmSubsidy) {
        this.warmSubsidy = warmSubsidy == null ? null : warmSubsidy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PENSION_PERSONAL_PERCENT
     *
     * @return the value of STAFF_SALARY.PENSION_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPensionPersonalPercent() {
        return pensionPersonalPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PENSION_PERSONAL_PERCENT
     *
     * @param pensionPersonalPercent the value for STAFF_SALARY.PENSION_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPensionPersonalPercent(String pensionPersonalPercent) {
        this.pensionPersonalPercent = pensionPersonalPercent == null ? null : pensionPersonalPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PENSION_COMPANY_PERCENT
     *
     * @return the value of STAFF_SALARY.PENSION_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPensionCompanyPercent() {
        return pensionCompanyPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PENSION_COMPANY_PERCENT
     *
     * @param pensionCompanyPercent the value for STAFF_SALARY.PENSION_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPensionCompanyPercent(String pensionCompanyPercent) {
        this.pensionCompanyPercent = pensionCompanyPercent == null ? null : pensionCompanyPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.MEDICAL_PERSONAL_PERCENT
     *
     * @return the value of STAFF_SALARY.MEDICAL_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getMedicalPersonalPercent() {
        return medicalPersonalPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.MEDICAL_PERSONAL_PERCENT
     *
     * @param medicalPersonalPercent the value for STAFF_SALARY.MEDICAL_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setMedicalPersonalPercent(String medicalPersonalPercent) {
        this.medicalPersonalPercent = medicalPersonalPercent == null ? null : medicalPersonalPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.MEDICAL_COMPANY_PERCENT
     *
     * @return the value of STAFF_SALARY.MEDICAL_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getMedicalCompanyPercent() {
        return medicalCompanyPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.MEDICAL_COMPANY_PERCENT
     *
     * @param medicalCompanyPercent the value for STAFF_SALARY.MEDICAL_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setMedicalCompanyPercent(String medicalCompanyPercent) {
        this.medicalCompanyPercent = medicalCompanyPercent == null ? null : medicalCompanyPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.UNEMPLOYMENT_PERSONAL_PERCENT
     *
     * @return the value of STAFF_SALARY.UNEMPLOYMENT_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getUnemploymentPersonalPercent() {
        return unemploymentPersonalPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.UNEMPLOYMENT_PERSONAL_PERCENT
     *
     * @param unemploymentPersonalPercent the value for STAFF_SALARY.UNEMPLOYMENT_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setUnemploymentPersonalPercent(String unemploymentPersonalPercent) {
        this.unemploymentPersonalPercent = unemploymentPersonalPercent == null ? null : unemploymentPersonalPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.UNEMPLOYMENT_COMPANY_PERCENT
     *
     * @return the value of STAFF_SALARY.UNEMPLOYMENT_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getUnemploymentCompanyPercent() {
        return unemploymentCompanyPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.UNEMPLOYMENT_COMPANY_PERCENT
     *
     * @param unemploymentCompanyPercent the value for STAFF_SALARY.UNEMPLOYMENT_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setUnemploymentCompanyPercent(String unemploymentCompanyPercent) {
        this.unemploymentCompanyPercent = unemploymentCompanyPercent == null ? null : unemploymentCompanyPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.INJURY_COMPANY_PERCENT
     *
     * @return the value of STAFF_SALARY.INJURY_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getInjuryCompanyPercent() {
        return injuryCompanyPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.INJURY_COMPANY_PERCENT
     *
     * @param injuryCompanyPercent the value for STAFF_SALARY.INJURY_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setInjuryCompanyPercent(String injuryCompanyPercent) {
        this.injuryCompanyPercent = injuryCompanyPercent == null ? null : injuryCompanyPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.BIRTH_COMPAY_PERCENT
     *
     * @return the value of STAFF_SALARY.BIRTH_COMPAY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getBirthCompayPercent() {
        return birthCompayPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.BIRTH_COMPAY_PERCENT
     *
     * @param birthCompayPercent the value for STAFF_SALARY.BIRTH_COMPAY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setBirthCompayPercent(String birthCompayPercent) {
        this.birthCompayPercent = birthCompayPercent == null ? null : birthCompayPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.ACTUAL_SALARY
     *
     * @return the value of STAFF_SALARY.ACTUAL_SALARY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getActualSalary() {
        return actualSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.ACTUAL_SALARY
     *
     * @param actualSalary the value for STAFF_SALARY.ACTUAL_SALARY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setActualSalary(String actualSalary) {
        this.actualSalary = actualSalary == null ? null : actualSalary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PERSONAL_TOTAL
     *
     * @return the value of STAFF_SALARY.PERSONAL_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPersonalTotal() {
        return personalTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PERSONAL_TOTAL
     *
     * @param personalTotal the value for STAFF_SALARY.PERSONAL_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPersonalTotal(String personalTotal) {
        this.personalTotal = personalTotal == null ? null : personalTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.COMPANY_TOTAL
     *
     * @return the value of STAFF_SALARY.COMPANY_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getCompanyTotal() {
        return companyTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.COMPANY_TOTAL
     *
     * @param companyTotal the value for STAFF_SALARY.COMPANY_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setCompanyTotal(String companyTotal) {
        this.companyTotal = companyTotal == null ? null : companyTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.PAYMENT_TOTAL
     *
     * @return the value of STAFF_SALARY.PAYMENT_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getPaymentTotal() {
        return paymentTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.PAYMENT_TOTAL
     *
     * @param paymentTotal the value for STAFF_SALARY.PAYMENT_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setPaymentTotal(String paymentTotal) {
        this.paymentTotal = paymentTotal == null ? null : paymentTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_BASE_PERSONAL
     *
     * @return the value of STAFF_SALARY.HOUSE_BASE_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseBasePersonal() {
        return houseBasePersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_BASE_PERSONAL
     *
     * @param houseBasePersonal the value for STAFF_SALARY.HOUSE_BASE_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseBasePersonal(String houseBasePersonal) {
        this.houseBasePersonal = houseBasePersonal == null ? null : houseBasePersonal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_BASE_COMPANY
     *
     * @return the value of STAFF_SALARY.HOUSE_BASE_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseBaseCompany() {
        return houseBaseCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_BASE_COMPANY
     *
     * @param houseBaseCompany the value for STAFF_SALARY.HOUSE_BASE_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseBaseCompany(String houseBaseCompany) {
        this.houseBaseCompany = houseBaseCompany == null ? null : houseBaseCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_SUPPLY_PERSONAL
     *
     * @return the value of STAFF_SALARY.HOUSE_SUPPLY_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseSupplyPersonal() {
        return houseSupplyPersonal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_SUPPLY_PERSONAL
     *
     * @param houseSupplyPersonal the value for STAFF_SALARY.HOUSE_SUPPLY_PERSONAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseSupplyPersonal(String houseSupplyPersonal) {
        this.houseSupplyPersonal = houseSupplyPersonal == null ? null : houseSupplyPersonal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_SUPPLY_COMPANY
     *
     * @return the value of STAFF_SALARY.HOUSE_SUPPLY_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseSupplyCompany() {
        return houseSupplyCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_SUPPLY_COMPANY
     *
     * @param houseSupplyCompany the value for STAFF_SALARY.HOUSE_SUPPLY_COMPANY
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseSupplyCompany(String houseSupplyCompany) {
        this.houseSupplyCompany = houseSupplyCompany == null ? null : houseSupplyCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_BASE_PERSONAL_PERCENT
     *
     * @return the value of STAFF_SALARY.HOUSE_BASE_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseBasePersonalPercent() {
        return houseBasePersonalPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_BASE_PERSONAL_PERCENT
     *
     * @param houseBasePersonalPercent the value for STAFF_SALARY.HOUSE_BASE_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseBasePersonalPercent(String houseBasePersonalPercent) {
        this.houseBasePersonalPercent = houseBasePersonalPercent == null ? null : houseBasePersonalPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_BASE_COMPANY_PERCENT
     *
     * @return the value of STAFF_SALARY.HOUSE_BASE_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseBaseCompanyPercent() {
        return houseBaseCompanyPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_BASE_COMPANY_PERCENT
     *
     * @param houseBaseCompanyPercent the value for STAFF_SALARY.HOUSE_BASE_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseBaseCompanyPercent(String houseBaseCompanyPercent) {
        this.houseBaseCompanyPercent = houseBaseCompanyPercent == null ? null : houseBaseCompanyPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_SUPPLY_PERSONAL_PERCENT
     *
     * @return the value of STAFF_SALARY.HOUSE_SUPPLY_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseSupplyPersonalPercent() {
        return houseSupplyPersonalPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_SUPPLY_PERSONAL_PERCENT
     *
     * @param houseSupplyPersonalPercent the value for STAFF_SALARY.HOUSE_SUPPLY_PERSONAL_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseSupplyPersonalPercent(String houseSupplyPersonalPercent) {
        this.houseSupplyPersonalPercent = houseSupplyPersonalPercent == null ? null : houseSupplyPersonalPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_SUPPLY_COMPANY_PERCENT
     *
     * @return the value of STAFF_SALARY.HOUSE_SUPPLY_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseSupplyCompanyPercent() {
        return houseSupplyCompanyPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_SUPPLY_COMPANY_PERCENT
     *
     * @param houseSupplyCompanyPercent the value for STAFF_SALARY.HOUSE_SUPPLY_COMPANY_PERCENT
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseSupplyCompanyPercent(String houseSupplyCompanyPercent) {
        this.houseSupplyCompanyPercent = houseSupplyCompanyPercent == null ? null : houseSupplyCompanyPercent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_PERSONAL_TOTAL
     *
     * @return the value of STAFF_SALARY.HOUSE_PERSONAL_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHousePersonalTotal() {
        return housePersonalTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_PERSONAL_TOTAL
     *
     * @param housePersonalTotal the value for STAFF_SALARY.HOUSE_PERSONAL_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHousePersonalTotal(String housePersonalTotal) {
        this.housePersonalTotal = housePersonalTotal == null ? null : housePersonalTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_COMPANY_TOTAL
     *
     * @return the value of STAFF_SALARY.HOUSE_COMPANY_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseCompanyTotal() {
        return houseCompanyTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_COMPANY_TOTAL
     *
     * @param houseCompanyTotal the value for STAFF_SALARY.HOUSE_COMPANY_TOTAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseCompanyTotal(String houseCompanyTotal) {
        this.houseCompanyTotal = houseCompanyTotal == null ? null : houseCompanyTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAFF_SALARY.HOUSE_TOATAL
     *
     * @return the value of STAFF_SALARY.HOUSE_TOATAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public String getHouseToatal() {
        return houseToatal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAFF_SALARY.HOUSE_TOATAL
     *
     * @param houseToatal the value for STAFF_SALARY.HOUSE_TOATAL
     *
     * @mbggenerated Wed Aug 16 11:02:36 CST 2017
     */
    public void setHouseToatal(String houseToatal) {
        this.houseToatal = houseToatal == null ? null : houseToatal.trim();
    }
}